# Generated by Django 6.0.2 on 2026-02-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='parent_feedback',
            old_name='feedback_reply',
            new_name='reply',
        ),
        migrations.RenameField(
            model_name='staff_feedback',
            old_name='feedback_reply',
            new_name='reply',
        ),
    ]
